#!/bin/tcsh

#Cannot run topup because only have 1 direction 

#run eddy  correction

eddy_openmp --imain=${n}_dwi.nii.gz --mask=${n}_brain_mask.nii.gz --index=index.txt --acqp=acqparamsAP_PA.txt --bvecs=${n}_bvecs --bvals=${n}_bvals --fwhm=0 --flm=quadratic --repol --dont_peas --out=${n}_eddy

echo ${n} 

end 
